### PR TITLE
Make GaussianBeam work on Debian 12 (bookworm) with qt5, since qt4 was deleted from Debian repos.

### PR DESCRIPTION
**Pull request by mer0m**

### CODE REVIEW

**Comment by DanHickstein** [comment]
Thanks for doing this! For some reason, the PNG files all got replaced with (seemingly) identical PNG images. Do you mind fixing this? Maybe we should add ".png" to the gitignore too.

**Comment by mer0m** [comment]
The content of the png files is strictly identical. 
I only removed the execution rights (since it's not mandatory to load them).

**Comment by DanHickstein** [comment]
Okay, sounds good. Merged.

**Comment by DanHickstein** [comment]
Thanks!!

**Pull request merged**
